#!/bin/bash

user=$1
pass=$2
masaaktif=$3

source /usr/bin/main.sh

is_user_free() {
    check_sysuser=$(cut -f 1 -d : /etc/passwd | grep "^$user$" )
    if [ ! -z "$check_sysuser" ] || [ -e "$USER_DATA" ]; then
        check_result $E_EXISTS "user $user exists"
    fi
}

check_args '3' "$#" 'USER PASSWORD EXPIRED'
is_user_free "$user"

useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $user
check_result $? "user creation failed" $E_INVALID
echo -e "$pass\n$pass\n"|passwd $user &> /dev/null

exit
