#!/bin/bash

user=$1

source /usr/bin/main.sh


check_args '1' "$#" 'USERNAME'

if getent passwd $user > /dev/null 2>&1; then
        userdel $user
        check_result $? "user deleted failed" $E_INVALID
else
        echo -e "Error: User $user no exits"
        exit 1
fi

exit
